name: Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: build-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/bin/Release/
            **/obj/
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Check for Test Projects
        id: check_tests
        run: |
          if [ -z "$(find . -name '*.csproj' -exec grep -l '<ProjectReference Include=.*Test' {} +)" ]; then
            echo "NO_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Run Tests
        if: env.NO_TESTS != 'true'
        run: dotnet test --no-build --configuration Release --verbosity normal

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=WesselKuijstermans_AvansDevOps
            -Dsonar.organization=wesselkuijstermans-1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
