name: Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: build-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore NuGet Packages
        run: dotnet restore ./AvansDevOps/AvansDevOps.sln

      - name: Clean previous builds
        run: dotnet clean ./AvansDevOps/AvansDevOps.sln

      - name: Build project
        run: dotnet build ./AvansDevOps/AvansDevOps.sln --no-restore --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/bin/Release/
            **/obj/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Install dotnet-coverage tool
        run: dotnet tool install --global dotnet-coverage

      - name: Run Tests and Collect Coverage
        run: |
          dotnet sonarscanner begin /k:"WesselKuijstermans_AvansDevOps"
              /d:sonar.token="wesselkuijstermans-1"
              /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet sonarscanner end /d:sonar.token="wesselkuijstermans-1"

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=WesselKuijstermans_AvansDevOps
            -Dsonar.organization=wesselkuijstermans-1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
