name: Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: build-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore ./AvansDevOps/AvansDevOps.sln

      - name: Clean previous builds
        run: dotnet clean ./AvansDevOps/AvansDevOps.sln

      - name: Build project
        run: dotnet build ./AvansDevOps/AvansDevOps.sln --no-restore --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/bin/Release/
            **/obj/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
  
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
  
      - name: Run Coverlet Coverage
        id: coverlet
        uses: b3b00/coverlet-action@1.2.5
        with:
          testProject: 'AvansDevOpsTest/AvansDevOpsTest.csproj'
          output: 'coverage.cobertura.xml'
          outputFormat: 'cobertura'
          debug: true

      - name: Find coverage files
        run: find . -name '*.xml'
  
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./AvansDevOpsTest/TestResults/coverage.cobertura.xml

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Run SonarCloud Analysis
        run: |
          dotnet sonarscanner begin /k:"WesselKuijstermans_AvansDevOps" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /o:wesselkuijstermans-1 \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.coverageReportPaths=coverage/coverage.cobertura.xml
          dotnet build ./AvansDevOps/AvansDevOps.sln --no-incremental
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
