name: Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: build-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore ./AvansDevOps/AvansDevOps.sln

      - name: Clean previous builds
        run: dotnet clean ./AvansDevOps/AvansDevOps.sln

      - name: Build project
        run: dotnet build ./AvansDevOps/AvansDevOps.sln --no-restore --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/bin/Release/
            **/obj/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
  
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
  
      - name: Run Tests and Generate Coverage
        run: |
          mkdir -p TestResults
          cd AvansDevOpsTest && dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:coberturaOutputFormat=cobertura /p:coberturaOutput=TestResults/coverage.cobertura.xml

      - name: check file location
        run: find . -name '*.xml'

      - name: Show coverage file details
        run: |
          echo "File size:"
          stat ./AvansDevOpsTest/TestResults/coverage.cobertura.xml || echo "File not found"
          echo "File contents:"
          cat ./AvansDevOpsTest/TestResults/coverage.cobertura.xml || echo "No contents"
  
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./AvansDevOpsTest/TestResults/coverage.cobertura.xml

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet coverage
        run: dotnet tool install --global dotnet-coverage
      
      - name: SonarCloud Begin
        run: |
          dotnet sonarscanner begin \
            /k:"WesselKuijstermans_AvansDevOps" \
            /o:"wesselkuijstermans-1" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.cobertura.reportsPaths=coverage/coverage.cobertura.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build solution
        run: dotnet build AvansDevOps/AvansDevOps.sln --no-incremental --configuration Release
      
      - name: Collect Cobertura coverage
        run: |
          mkdir -p coverage
          dotnet-coverage collect \
            'dotnet test AvansDevOpsTest/AvansDevOpsTest.csproj --no-build --configuration Release' \
            --output coverage/coverage.cobertura.xml \
            --output-format cobertura
      
      - name: Dump coverage (debug)
        run: cat coverage/coverage.cobertura.xml
      
      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
